### PR TITLE
Solid principles

### PR DESCRIPTION
**Pull request by 29td**
### Project Milestone: refactor your code
_In this PR the following was implemented:_

YAGNI, KISS, and DRY rules and Ruby style guide are respected.

**_Follow SOLID principles._**

- "Single-responsibility Principle".
- Role of main.rb is only to start the code and ask the user for the initial choice of options (or to quit).
- Extract some pieces of logic into a separate class Select.

### CODE REVIEW

**Review by thecodechaser — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @29td, and Team👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️



## Required Changes ♻️

- [ ] https://github.com/29td/oop-school-libriary/blob/240fa356610c789cf163fa46e395297cb5790b6d/app.rb#L21-L31
 Here you are getting input from users and creating the student, This method does not follow the `single responsibility principle`. Please make sure to separate these operations into different methods to achieve the `single responsibility principle`.

- [ ] https://github.com/29td/oop-school-libriary/blob/240fa356610c789cf163fa46e395297cb5790b6d/app.rb#L32-L42
Here you are getting input from users and creating the teacher, This method does not follow the `single responsibility principle`. Please make sure to separate these operations into different methods to achieve the `single responsibility principle.

- [ ] https://github.com/29td/oop-school-libriary/blob/240fa356610c789cf163fa46e395297cb5790b6d/app.rb#L46-L55
In the `add_book` method you are getting input from users and creating the book, This method does not follow the `single responsibility principle`. Please make sure to separate these operations into different methods to achieve the `single responsibility principle.

- [ ] https://github.com/29td/oop-school-libriary/blob/240fa356610c789cf163fa46e395297cb5790b6d/app.rb#L57-L70
In the `add_rental` method you are getting input from users and creating the rental, This method does not follow the `single responsibility principle`. Please make sure to separate these operations into different methods to achieve the `single responsibility principle.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by 29td** [comment]
hy @thecodechaser 
Thank you for the review but The project requirements wanted us to fix the main.rb file not the app.rb file as it was approved from the previous project so the required should be optional.

**Comment by thecodechaser** [comment]
@29td Hi,
The project requirements say to extract code from the `main.rb` to other files because of its length. You should refactor the code in all of the classes. I would suggest you do that. It is a good practice to write clean code.
If you still have any questions or concerns, please let me know. I would be happy to assist.

**Comment by 29td** [comment]
hy again @thecodechaser 
Screenshot (94)
I think there is a misunderstanding here as you can see the last point it says we have to Extract some pieces of logic into separate class(es) which is done on the refractor.rb file 
_Cheers happpy reviewing 😄 _

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @29td , This is @sja-thedude your code reviewer.

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

200w

 ## Highlights
✔️ Good job so far

 ## Required Changes ♻️
- [ ] @29td You are right that the changes you made were required for the project. main.rb file was supposed to only have the code to start the app and which you have. Also, you made a different file to separate the class, however, one of the requirements is also to follow the single responsibility principle and it is required in order to get the project approved. You have to make the changes asked by the previous reviewer in order to proceed. If you still have any doubt or think this is not valid then you could ask for second opinion.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by bimbolabuari — COMMENTED** [review]
Hello @29td  👋, 

_This is an additional review as a result of the second opinion request._ 

- I understand that it was stated in the project requirement to refactor the `main.rb` file, however, the previous CRs were not wrong with their requested changes because we explicitly stated that the single responsibility principle should also be checked in the `app.rb` file according to the code review guideline. 

>  In other to make your code cleaner and follow the "Single-responsibility Principle, I strongly suggest you implement the requested changes. 

 As this was the only reason that your project was not approved it will be approved as soon as possible. 
Please implement the requested changes and ask for another review in your Dashboard and the next Code Reviewer will mark it as approved right away :) 
Keep rocking 🚀!

**Comment by 29td** [comment]
hy @bimbolabuari 
Thank you for the comments. changes were made can you please check for me if it is correct now.

**Review by dasileker — APPROVED** [review]
### **Hi @29td,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
